apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.2/manifests/install.yaml
#- https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.4/manifests/ha/install.yaml

patches:
- path: application-controller.yaml
- path: repo-server.yaml
- path: server.yaml
- path: dex-server.yaml
#namePrefix: test-