apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: default
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        name: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6.5
        ports:
          - containerPort: 3306
        env:
          - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
            value: "yes"
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 10Gi