apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sommerphilipp/homelab
    targetRevision: main
    path: sealedsecrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true